feat: Added "common films" functionality
rocketman27/java-filmorate pull request #10
Opened 2022-08-17 20:51 UTC by dev1ce13

2022-08-17 21:50 UTC, rocketman27 reviewed
Общая рекомендация - подождать пока будет залит https://github.com/rocketman27/java-filmorate/pull/8, после этого сделать rebase от ветки develop, протестировать, что все работает и обновить твой PR ;-)

2022-08-17 21:50 UTC, rocketman27 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +import org.springframework.web.bind.annotation.*;
Лучше не использовать wildcard в импортах

https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad

2022-08-17 21:50 UTC, rocketman27 commented on src/main/resources/schema.sql
> +/*drop table IF EXISTS FILMS_GENRES;
Лучше не держать такие комментарии в коде

2022-08-17 21:50 UTC, rocketman27 commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/FilmServiceImpl.java
> +import ru.yandex.practicum.filmorate.dao.*;
Лучше не использовать wildcard в импортах, а указывать классы явно

2022-08-17 21:50 UTC, rocketman27 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +                "SELECT F.*, M.MPA_NAME " +
будет конфликт с изменениями Алексея, сущность переименовали mpa_name -> name

2022-08-17 21:50 UTC, rocketman27 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.info("/GET вывод списка общих фильмов");
In English? :)

2022-08-18 03:43 UTC, SimpleTrooper requested changes

2022-08-18 03:43 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +            throw new UserNotFoundException(String.format("User with id=%s or id=%s doesn't exist", userId, friendId));
Если запрос пустой - метод query вернет пустой список, а не выдаст исключение. https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html. Также код выбрасывает исключение UserNotFound, хотя пользователи в БД могут существовать, но лайков к фильмам не поставить. Скорее здесь нужна проверка на существование пользователей в сервисе

2022-08-18 03:43 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/FilmServiceImpl.java
> +        log.info("Received request to get a list of common movies of users with ID " + userId + " and " + friendId);
Здесь можно добавить проверку на существование пользователей и, если что, выбрасывать UserNotFound

2022-08-19 12:25 UTC, closed without merging