Feat: Added reviews
rocketman27/java-filmorate pull request #13
Opened 2022-08-19 20:58 UTC by beginnerproga

Добавил контроллер для комментариев ReviewController, 
сервис для комментариев ReviewService, 
два dao ReviewDaoImpl и LikesReviewDaoImpl,
две модели Review и LikeForReview 
новое исключение ReviewNotFoundException,
реализованы две новые таблицы Reviews и Reviews_Users_Likes

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +import org.springframework.web.bind.annotation.*;
Укажи конкретные аннотации

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +    public List<Review> getReviewsByFilmId(@RequestParam(required = false) Long filmId, @RequestParam(required = false) Integer count) {
Сделай через defaultValue="10"

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ReviewController.java
> +        else return reviewService.getReviewsByFilmId(filmId, count);
По желанию, я бы сделал 1 метод getReviews в сервисе, а вот уже в сервисе проверку на null filmId, и в dao уже 2 метода, вывод всех отзывов, либо на конкретный фильм

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDao.java
> +    Film updateFilm(Film film);
Пусть останется старая реализация все таки)

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDao.java
> +    void removeUser(long id);
Почему то тут не твой код, исправь)

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +                        "SELECT FILM_ID, " +
Тоже не твой код)

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +    public Film updateFilm(Film film) {
Пусть старое будет, не существенно

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +       review =  reviewDao.addReview(review);
Можно просто return reviewDao.addReview(review);

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +    @Override
сделай перед каждым @Override пустую строку

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/ReviewDao.java
> +     void incrementUseful(long id);
Мне кажется подобные методы лучше сделать private и обращаться к ним из нужных методов уже в daoImpl

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/models/Review.java
> +import lombok.*;
Лучше необходимые аннотации)

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/models/Review.java
> +    private  Integer userId;
Тут лучше сделать User user, как в Film у нас не int mpa_id, а Mpa mpa

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/models/Review.java
> +    private  Integer filmId;
Тоже самое, надо Film film

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/models/Review.java
> +    private Set<LikeForReview> likesForReview = new HashSet<>();
Не очень понятно зачем класс LikeForReview, нужна же по сути такая же реализация как в в Film, достаточно просто Set<User> likes

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/models/Review.java
> +    public void incrementUseful(){
В методах нет смысла, так как все обращения к базе идут, у тебя же вроде есть запрос на useful-1

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/services/ReviewService.java
> +    List<Review> getReviews(int count);
Вот тут лучше 1 метод с параметрами filmId и count

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/resources/schema.sql
> +    foreign key (USER_ID) references USERS (USER_ID)
тут ON DELETE CASCADE, а то удаление пользователя не будет работать

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/models/LikeForReview.java
> +public class LikeForReview {
не вижу смысла этого класса

2022-08-20 13:53 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/LikesReviewDao.java
> +    void addUserLikesForReview(long reviewId, long userId, boolean type);
лучше addLikeForReview, без user, но вообще не имеет значения)

2022-08-21 09:13 UTC, SimpleTrooper requested changes

2022-08-21 09:13 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +        }
Также проверку на пользователя и фильм

2022-08-21 09:13 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +        likesReviewDao.addUserLikesForReview(review);
Лишний метод, лайки можно не выводить - дополнительная нагрузка на БД. Кстати, в методе add отсутствует добавление лайков и тесты постмана проходятся

2022-08-21 09:13 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +        likesReviewDao.deleteUserLikesByReviewId(id);
Лишний метод. В БД можно сделать каскадное удаление

2022-08-21 09:13 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +    List<LikeForReview> likesForReview = likesReviewDao.getUserLikesByReviewId(id);
Лишний запрос к БД

2022-08-21 09:13 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +        reviews.stream().forEach(review->review.setLikesForReview(new HashSet<>(likesReviewDao.getUserLikesByReviewId(review.getReviewId()))));
Лишние запросы к БД

2022-08-21 09:13 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +    @Override
code style. ctrl+alt+l в IDEA

2022-08-21 09:13 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +       reviews.stream().forEach(review->review.setLikesForReview(new HashSet<>(likesReviewDao.getUserLikesByReviewId(review.getReviewId()))));
Лишние запросы к БД

2022-08-21 09:13 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +        reviewDao.getReviewById(id).incrementUseful();
Было бы здорово, если бы поле useful увеличивалось в DAO

2022-08-21 09:13 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +        likesReviewDao.deleteUserLikesByReviewId(id,userId,false);
Вот здесь название метода начинает начинает вызывать некоторую путаницу, не сразу понятно - что именно делает код. Например, у меня первая ассоциация, что метод удаляет все лайки для ревью с определенным id.

2022-08-21 09:13 UTC, SimpleTrooper commented on src/main/resources/schema.sql
> +create table if not exists REVIEWS_USERS_LIKES
Лучше переименовать в reviews_likes + code style. ctrl+alt+l в IDEA

2022-08-23 15:56 UTC, SimpleTrooper requested changes

2022-08-23 15:56 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/LikesReviewDaoImpl.java
> +    private final ReviewDao reviewDao;
Зависимость DAO от DAO - мой ревьюер не примет )

2022-08-23 15:56 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/LikesReviewDaoImpl.java
> +            reviewDao.incrementUseful(reviewId);
Вместо вызова метода из reviewDao можно сделать приватный метод в этом DAO с запросом к БД

2022-08-23 15:56 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/LikesReviewDaoImpl.java
> +    public void deleteLikeForReview(long reviewId) {
Этот метод где-то используется? Думаю, что он лишний, лайки удаляются каскадом в БД при удалении ревью

2022-08-23 15:56 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/LikesReviewDaoImpl.java
> +        if (updatedRows == 1) {
Вот здесь код неверно будет работать, т.к. у нас количество удаленных лайков может быть любым

2022-08-23 15:56 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +            throw new UserNotFoundException("User with id = " + review.getUserId() + " not found");
Тут не исправлено - лучше проверить в сервисе, а здесь удалить лишние проверки

2022-08-23 15:56 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +    public List<Review> getReviewByFilmId(long filmId, int count) {
Множественное число - getReviews

2022-08-23 15:56 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +    public void incrementUseful(long id) {
Лучше их перенести в LikesReviewDaoImpl и сделать приватными

2022-08-23 15:56 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/models/Review.java
> +    public boolean getIsPositive() {
Лишний метод

2022-08-23 15:56 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/models/Review.java
> +    public Map<String, Object> toMap() {
Метод не используется, у тебя добавление по-другому сделано. Думаю, что лучше удалить

2022-08-23 15:56 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +        }
Не добавлена проверка пользователя и фильма

2022-08-23 15:56 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/ReviewServiceImpl.java
> +        }
+

2022-08-23 16:11 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        if (review.getUserId() < 0)
Какие-то костыльные проверки, код не выбросит исключение если id=4, а в базе 3 пользователя, лучше вызови в сервисе метод getUerById, там уже эта логика реализована

2022-08-23 16:11 UTC, dev1ce13 commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/ReviewDaoImpl.java
> +        else if (review.getFilmId() < 0)
тут тоже самое

2022-08-23 18:08 UTC, dev1ce13 approved these changes

2022-08-23 18:21 UTC, SimpleTrooper approved these changes
Нужно засквошить в один коммит

2022-08-23 18:53 UTC, merged