feat:Added remove function for Users and Films
rocketman27/java-filmorate pull request #9
Opened 2022-08-17 19:32 UTC by Ksenia91Dumina

2022-08-19 18:40 UTC, SimpleTrooper requested changes

2022-08-19 18:40 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +        user.setId(userId);
Повторная вставка - упадем с исключением

2022-08-19 18:40 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +        if (result >0) {
Пробел, после знака неравенства (ctrl+alt+l в IDEA - автоматом подравняет)

2022-08-19 18:40 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDaoImpl.java
> +        if ( result> 0) {
Тоже пробел

2022-08-19 18:40 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/FilmServiceImpl.java
> +import java.util.*;
Лучше указывать импорты каждый по-отдельности

2022-08-19 18:40 UTC, SimpleTrooper commented on src/main/java/ru/yandex/practicum/filmorate/services/impl/FilmServiceImpl.java
> +    private void removeGenreDuplicates(Film film) {
Этот метод не нужен, его после ребейза должно было удалить

2022-08-19 18:40 UTC, SimpleTrooper commented on src/main/resources/schema.sql
> +        foreign key (MPA_ID) references MPA ON DELETE CASCADE
Не уверен, что стоит удалять все фильмы, после удаления рейтинга. Хотя тут вопрос открытый

2022-08-20 09:54 UTC, SimpleTrooper approved these changes

2022-08-20 10:40 UTC, dev1ce13 approved these changes

2022-08-20 10:47 UTC, merged